In [2]:
%pylab inline
%load_ext autoreload
%autoreload 2

Populating the interactive namespace from numpy and matplotlib

In [3]:
import os
import numpy as np
import pandas as pd
import baostock as bs

import sys
sys.path.append('..')

In [4]:
path = '..\\db'

In [5]:
lg = bs.login()

login success!

### K线信息

In [7]:
stock_code = 'sh.600000'
fields = 'date,code,open,high,low,close,preclose,volume,amount,adjustflag,\
         turn,tradestatus,pctChg,isST'
start_date = '2017-07-01'
end_date = '2017-12-31'
    
rs = bs.query_history_k_data_plus(
                                    stock_code, 
                                    fields, 
                                    start_date=start_date, 
                                    end_date=end_date,
                                    frequency='d', 
                                    adjustflag='3'
)

In [8]:
data_list = []
while (rs.error_code == '0') & rs.next():
    data_list.append(rs.get_row_data())
    
result = pd.DataFrame(data_list, columns=rs.fields)

In [9]:
result

,date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST
0,2017-07-03,sh.600000,12.6400,12.6500,12.4700,12.5600,12.6500,38778949,486264672.0000,3,0.137985,1,-0.711456,0
1,2017-07-04,sh.600000,12.5500,12.5800,12.4100,12.5500,12.5600,36659128,458434432.0000,3,0.130442,1,-0.079620,0
2,2017-07-05,sh.600000,12.5000,12.6500,12.4700,12.6200,12.5500,26470507,332542464.0000,3,0.094188,1,0.557767,0
3,2017-07-06,sh.600000,12.6200,12.7200,12.5100,12.6600,12.6200,37414241,471582096.0000,3,0.133129,1,0.316957,0
4,2017-07-07,sh.600000,12.6200,12.6900,12.5500,12.6000,12.6600,24667294,311101536.0000,3,0.087772,1,-0.473929,0
5,2017-07-10,sh.600000,12.5900,12.6400,12.5200,12.5300,12.6000,26411530,331940512.0000,3,0.093979,1,-0.555561,0
6,2017-07-11,sh.600000,12.5100,12.9400,12.5100,12.8000,12.5300,96835349,1238626608.0000,3,0.344564,1,2.154832,0
7,2017-07-12,sh.600000,12.8000,13.0600,12.7400,12.8600,12.8000,80469025,1039614032.0000,3,0.286328,1,0.468746,0
8,2017-07-13,sh.600000,12.8200,13.2900,12.7700,13.2700,12.8600,110219238,1436784304.0000,3,0.392187,1,3.188187,0
9,2017-07-14,sh.600000,13.3400,13.8000,13.3400,13.5900,13.2700,146865370,1991795312.0000,3,0.522583,1,2.411452,0
10,2017-07-17,sh.600000,13.6200,14.0200,13.2800,13.7600,13.5900,178661221,2448349168.0000,3,0.635720,1,1.250920,0
11,2017-07-18,sh.600000,13.6500,13.7200,13.4000,13.5500,13.7600,69895876,946717552.0000,3,0.248706,1,-1.526163,0
12,2017-07-19,sh.600000,13.5600,13.7800,13.4800,13.6900,13.5500,66108709,900014400.0000,3,0.235231,1,1.033206,0
13,2017-07-20,sh.600000,13.6700,13.7000,13.5300,13.6200,13.6900,40017492,544175216.0000,3,0.142392,1,-0.511320,0
14,2017-07-21,sh.600000,13.6100,13.6300,13.3800,13.4500,13.6200,52272375,702999232.0000,3,0.185998,1,-1.248165,0
15,2017-07-24,sh.600000,13.4500,13.7400,13.3600,13.6700,13.4500,65820954,892033680.0000,3,0.234207,1,1.635690,0
16,2017-07-25,sh.600000,13.6200,13.7500,13.4100,13.5100,13.6700,58478099,795769072.0000,3,0.208079,1,-1.170445,0
17,2017-07-26,sh.600000,13.4500,13.7000,13.3600,13.3800,13.5100,57495388,775489072.0000,3,0.204583,1,-0.962251,0
18,2017-07-27,sh.600000,13.3800,13.4700,13.2800,13.3800,13.3800,33612097,449548320.0000,3,0.119600,1,0.000000,0
19,2017-07-28,sh.600000,13.3700,13.4900,13.3000,13.4700,13.3800,24954961,334111568.0000,3,0.088796,1,0.672647,0
20,2017-07-31,sh.600000,13.4500,13.5200,13.3100,13.3600,13.4700,45083081,602638880.0000,3,0.160417,1,-0.816634,0
21,2017-08-01,sh.600000,13.4200,13.4900,13.3200,13.4300,13.3600,64198064,860914608.0000,3,0.228432,1,0.523957,0
22,2017-08-02,sh.600000,13.4400,13.6000,13.3900,13.4400,13.4300,61644148,830433616.0000,3,0.219345,1,0.074455,0
23,2017-08-03,sh.600000,13.4200,13.4200,13.0400,13.0800,13.4400,78581867,1036842144.0000,3,0.279613,1,-2.678569,0
24,2017-08-04,sh.600000,13.0900,13.1000,12.8500,12.8700,13.0800,63181971,818014672.0000,3,0.224817,1,-1.605505,0
25,2017-08-07,sh.600000,12.8700,12.9500,12.8300,12.9300,12.8700,29528429,380518688.0000,3,0.105069,1,0.466204,0
26,2017-08-08,sh.600000,12.9100,12.9300,12.8300,12.8700,12.9300,23570298,303469936.0000,3,0.083869,1,-0.464040,0
27,2017-08-09,sh.600000,12.8400,12.8800,12.7500,12.7600,12.8700,32303821,413575792.0000,3,0.114945,1,-0.854698,0
28,2017-08-10,sh.600000,12.7400,12.8800,12.7000,12.7900,12.7600,44056044,563372048.0000,3,0.156762,1,0.235108,0
29,2017-08-11,sh.600000,12.7200,12.7300,12.4600,12.6800,12.7900,88890056,1118537328.0000,3,0.316292,1,-0.860044,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017-11-20,sh.600000,12.7000,12.8600,12.6100,12.8500,12.7800,61495420,783077227.0000,3,0.218816,1,0.547736,0
96,2017-11-21,sh.600000,12.8100,13.1700,12.7500,12.9400,12.8500,116179412,1512638142.0000,3,0.413394,1,0.700383,0
97,2017-11-22,sh.600000,13.0000,13.4400,13.0000,13.2300,12.9400,114576266,1513356223.0000,3,0.407690,1,2.241113,0
98,2017-11-23,sh.600000,13.2400,13.3200,12.9100,13.0600,13.2300,81912602,1076890039.0000,3,0.291465,1,-1.284952,0
99,2017-11-24,sh.600000,13.1100,13.1800,12.9300,13.0900,13.0600,59612483,777699709.0000,3,0.212116,1,0.229707,0
100,2017-11-27,sh.600000,13.0900,13.1200,12.8100,13.1000,13.0900,79250273,1028510255.0000,3,0.281992,1,0.076396,0
101,2017-11-28,sh.600000,13.0300,13.0700,12.9200,12.9400,13.1000,34031908,441466983.0000,3,0.121094,1,-1.221380,0
102,2017-11-29,sh.600000,12.9500,13.0400,12.8100,12.9400,12.9400,41846783,540439739.0000,3,0.148901,1,0.000000,0
103,2017-11-30,sh.600000,12.9100,12.9500,12.8000,12.9100,12.9400,39916356,513785829.0000,3,0.142032,1,-0.231837,0
104,2017-12-01,sh.600000,12.9300,12.9500,12.8100,12.9100,12.9100,38577445,496330241.0000,3,0.137268,1,0.000000,0
105,2017-12-04,sh.600000,12.8700,12.9400,12.8400,12.9200,12.9100,36479233,470155474.0000,3,0.129802,1,0.077461,0
106,2017-12-05,sh.600000,12.9200,13.2700,12.9100,13.1700,12.9200,123796797,1623138207.0000,3,0.440499,1,1.934985,0
107,2017-12-06,sh.600000,13.1200,13.1600,12.9100,12.9600,13.1700,43564931,566372423.0000,3,0.155015,1,-1.594533,0
108,2017-12-07,sh.600000,12.9500,13.0300,12.9100,12.9600,12.9600,34802229,451233524.0000,3,0.123835,1,0.000000,0
109,2017-12-08,sh.600000,12.9800,12.9900,12.8700,12.9300,12.9600,31296221,404411517.0000,3,0.111360,1,-0.231479,0
110,2017-12-11,sh.600000,12.9200,13.0400,12.8500,12.9700,12.9300,36649902,474566888.0000,3,0.130409,1,0.309358,0
111,2017-12-12,sh.600000,12.9700,12.9700,12.7400,12.7500,12.9700,30370097,390113096.0000,3,0.108064,1,-1.696224,0
112,2017-12-13,sh.600000,12.8000,12.8100,12.6300,12.7400,12.7500,19345338,246331123.0000,3,0.068835,1,-0.078433,0
113,2017-12-14,sh.600000,12.7900,12.7900,12.6600,12.6900,12.7400,16141678,205219487.0000,3,0.057436,1,-0.392466,0
114,2017-12-15,sh.600000,12.6900,12.7300,12.6100,12.6200,12.6900,16210108,205323767.0000,3,0.057679,1,-0.551613,0
115,2017-12-18,sh.600000,12.7100,12.7100,12.6100,12.6500,12.6200,13445648,170140035.0000,3,0.047843,1,0.237716,0
116,2017-12-19,sh.600000,12.6500,12.7600,12.6200,12.7500,12.6500,18399603,233884666.0000,3,0.065470,1,0.790517,0
117,2017-12-20,sh.600000,12.7600,12.7600,12.6000,12.7300,12.7500,26639844,337603451.0000,3,0.094791,1,-0.156866,0
118,2017-12-21,sh.600000,12.6700,12.7800,12.6000,12.7000,12.7300,21052388,267624195.0000,3,0.074909,1,-0.235662,0
119,2017-12-22,sh.600000,12.6800,12.7200,12.6100,12.6200,12.7000,16076938,203468779.0000,3,0.057206,1,-0.629921,0
120,2017-12-25,sh.600000,12.6100,12.6800,12.5600,12.5900,12.6200,19306662,243553698.0000,3,0.068698,1,-0.237716,0
121,2017-12-26,sh.600000,12.5700,12.6600,12.5600,12.6400,12.5900,15225722,192219131.0000,3,0.054177,1,0.397142,0
122,2017-12-27,sh.600000,12.6500,12.6600,12.5300,12.6200,12.6400,32731881,412197987.0000,3,0.116468,1,-0.158231,0
123,2017-12-28,sh.600000,12.6000,12.6600,12.5300,12.5400,12.6200,23870824,300834017.0000,3,0.084938,1,-0.633914,0
124,2017-12-29,sh.600000,12.5200,12.6200,12.5100,12.5900,12.5400,16351826,205752875.0000,3,0.058184,1,0.398726,0

In [8]:
result.iloc[:, 2:-1] = result.iloc[:, 2:-1].applymap(lambda x: float(x))
result['code'] = result['code'].apply(lambda x: x[3:] + '.' + x[0:2])

In [9]:
result

,date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST
0,2017-07-03,600000.sh,12.64,12.65,12.47,12.56,12.65,3.87789e+07,4.86265e+08,3,0.137985,1,-0.711456,0
1,2017-07-04,600000.sh,12.55,12.58,12.41,12.55,12.56,3.66591e+07,4.58434e+08,3,0.130442,1,-0.07962,0
2,2017-07-05,600000.sh,12.5,12.65,12.47,12.62,12.55,2.64705e+07,3.32542e+08,3,0.094188,1,0.557767,0
3,2017-07-06,600000.sh,12.62,12.72,12.51,12.66,12.62,3.74142e+07,4.71582e+08,3,0.133129,1,0.316957,0
4,2017-07-07,600000.sh,12.62,12.69,12.55,12.6,12.66,2.46673e+07,3.11102e+08,3,0.087772,1,-0.473929,0
5,2017-07-10,600000.sh,12.59,12.64,12.52,12.53,12.6,2.64115e+07,3.31941e+08,3,0.093979,1,-0.555561,0
6,2017-07-11,600000.sh,12.51,12.94,12.51,12.8,12.53,9.68353e+07,1.23863e+09,3,0.344564,1,2.15483,0
7,2017-07-12,600000.sh,12.8,13.06,12.74,12.86,12.8,8.0469e+07,1.03961e+09,3,0.286328,1,0.468746,0
8,2017-07-13,600000.sh,12.82,13.29,12.77,13.27,12.86,1.10219e+08,1.43678e+09,3,0.392187,1,3.18819,0
9,2017-07-14,600000.sh,13.34,13.8,13.34,13.59,13.27,1.46865e+08,1.9918e+09,3,0.522583,1,2.41145,0
10,2017-07-17,600000.sh,13.62,14.02,13.28,13.76,13.59,1.78661e+08,2.44835e+09,3,0.63572,1,1.25092,0
11,2017-07-18,600000.sh,13.65,13.72,13.4,13.55,13.76,6.98959e+07,9.46718e+08,3,0.248706,1,-1.52616,0
12,2017-07-19,600000.sh,13.56,13.78,13.48,13.69,13.55,6.61087e+07,9.00014e+08,3,0.235231,1,1.03321,0
13,2017-07-20,600000.sh,13.67,13.7,13.53,13.62,13.69,4.00175e+07,5.44175e+08,3,0.142392,1,-0.51132,0
14,2017-07-21,600000.sh,13.61,13.63,13.38,13.45,13.62,5.22724e+07,7.02999e+08,3,0.185998,1,-1.24816,0
15,2017-07-24,600000.sh,13.45,13.74,13.36,13.67,13.45,6.5821e+07,8.92034e+08,3,0.234207,1,1.63569,0
16,2017-07-25,600000.sh,13.62,13.75,13.41,13.51,13.67,5.84781e+07,7.95769e+08,3,0.208079,1,-1.17044,0
17,2017-07-26,600000.sh,13.45,13.7,13.36,13.38,13.51,5.74954e+07,7.75489e+08,3,0.204583,1,-0.962251,0
18,2017-07-27,600000.sh,13.38,13.47,13.28,13.38,13.38,3.36121e+07,4.49548e+08,3,0.1196,1,0,0
19,2017-07-28,600000.sh,13.37,13.49,13.3,13.47,13.38,2.4955e+07,3.34112e+08,3,0.088796,1,0.672647,0
20,2017-07-31,600000.sh,13.45,13.52,13.31,13.36,13.47,4.50831e+07,6.02639e+08,3,0.160417,1,-0.816634,0
21,2017-08-01,600000.sh,13.42,13.49,13.32,13.43,13.36,6.41981e+07,8.60915e+08,3,0.228432,1,0.523957,0
22,2017-08-02,600000.sh,13.44,13.6,13.39,13.44,13.43,6.16441e+07,8.30434e+08,3,0.219345,1,0.074455,0
23,2017-08-03,600000.sh,13.42,13.42,13.04,13.08,13.44,7.85819e+07,1.03684e+09,3,0.279613,1,-2.67857,0
24,2017-08-04,600000.sh,13.09,13.1,12.85,12.87,13.08,6.3182e+07,8.18015e+08,3,0.224817,1,-1.6055,0
25,2017-08-07,600000.sh,12.87,12.95,12.83,12.93,12.87,2.95284e+07,3.80519e+08,3,0.105069,1,0.466204,0
26,2017-08-08,600000.sh,12.91,12.93,12.83,12.87,12.93,2.35703e+07,3.0347e+08,3,0.083869,1,-0.46404,0
27,2017-08-09,600000.sh,12.84,12.88,12.75,12.76,12.87,3.23038e+07,4.13576e+08,3,0.114945,1,-0.854698,0
28,2017-08-10,600000.sh,12.74,12.88,12.7,12.79,12.76,4.4056e+07,5.63372e+08,3,0.156762,1,0.235108,0
29,2017-08-11,600000.sh,12.72,12.73,12.46,12.68,12.79,8.88901e+07,1.11854e+09,3,0.316292,1,-0.860044,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2017-11-20,600000.sh,12.7,12.86,12.61,12.85,12.78,6.14954e+07,7.83077e+08,3,0.218816,1,0.547736,0
96,2017-11-21,600000.sh,12.81,13.17,12.75,12.94,12.85,1.16179e+08,1.51264e+09,3,0.413394,1,0.700383,0
97,2017-11-22,600000.sh,13,13.44,13,13.23,12.94,1.14576e+08,1.51336e+09,3,0.40769,1,2.24111,0
98,2017-11-23,600000.sh,13.24,13.32,12.91,13.06,13.23,8.19126e+07,1.07689e+09,3,0.291465,1,-1.28495,0
99,2017-11-24,600000.sh,13.11,13.18,12.93,13.09,13.06,5.96125e+07,7.777e+08,3,0.212116,1,0.229707,0
100,2017-11-27,600000.sh,13.09,13.12,12.81,13.1,13.09,7.92503e+07,1.02851e+09,3,0.281992,1,0.076396,0
101,2017-11-28,600000.sh,13.03,13.07,12.92,12.94,13.1,3.40319e+07,4.41467e+08,3,0.121094,1,-1.22138,0
102,2017-11-29,600000.sh,12.95,13.04,12.81,12.94,12.94,4.18468e+07,5.4044e+08,3,0.148901,1,0,0
103,2017-11-30,600000.sh,12.91,12.95,12.8,12.91,12.94,3.99164e+07,5.13786e+08,3,0.142032,1,-0.231837,0
104,2017-12-01,600000.sh,12.93,12.95,12.81,12.91,12.91,3.85774e+07,4.9633e+08,3,0.137268,1,0,0
105,2017-12-04,600000.sh,12.87,12.94,12.84,12.92,12.91,3.64792e+07,4.70155e+08,3,0.129802,1,0.077461,0
106,2017-12-05,600000.sh,12.92,13.27,12.91,13.17,12.92,1.23797e+08,1.62314e+09,3,0.440499,1,1.93498,0
107,2017-12-06,600000.sh,13.12,13.16,12.91,12.96,13.17,4.35649e+07,5.66372e+08,3,0.155015,1,-1.59453,0
108,2017-12-07,600000.sh,12.95,13.03,12.91,12.96,12.96,3.48022e+07,4.51234e+08,3,0.123835,1,0,0
109,2017-12-08,600000.sh,12.98,12.99,12.87,12.93,12.96,3.12962e+07,4.04412e+08,3,0.11136,1,-0.231479,0
110,2017-12-11,600000.sh,12.92,13.04,12.85,12.97,12.93,3.66499e+07,4.74567e+08,3,0.130409,1,0.309358,0
111,2017-12-12,600000.sh,12.97,12.97,12.74,12.75,12.97,3.03701e+07,3.90113e+08,3,0.108064,1,-1.69622,0
112,2017-12-13,600000.sh,12.8,12.81,12.63,12.74,12.75,1.93453e+07,2.46331e+08,3,0.068835,1,-0.078433,0
113,2017-12-14,600000.sh,12.79,12.79,12.66,12.69,12.74,1.61417e+07,2.05219e+08,3,0.057436,1,-0.392466,0
114,2017-12-15,600000.sh,12.69,12.73,12.61,12.62,12.69,1.62101e+07,2.05324e+08,3,0.057679,1,-0.551613,0
115,2017-12-18,600000.sh,12.71,12.71,12.61,12.65,12.62,1.34456e+07,1.7014e+08,3,0.047843,1,0.237716,0
116,2017-12-19,600000.sh,12.65,12.76,12.62,12.75,12.65,1.83996e+07,2.33885e+08,3,0.06547,1,0.790517,0
117,2017-12-20,600000.sh,12.76,12.76,12.6,12.73,12.75,2.66398e+07,3.37603e+08,3,0.094791,1,-0.156866,0
118,2017-12-21,600000.sh,12.67,12.78,12.6,12.7,12.73,2.10524e+07,2.67624e+08,3,0.074909,1,-0.235662,0
119,2017-12-22,600000.sh,12.68,12.72,12.61,12.62,12.7,1.60769e+07,2.03469e+08,3,0.057206,1,-0.629921,0
120,2017-12-25,600000.sh,12.61,12.68,12.56,12.59,12.62,1.93067e+07,2.43554e+08,3,0.068698,1,-0.237716,0
121,2017-12-26,600000.sh,12.57,12.66,12.56,12.64,12.59,1.52257e+07,1.92219e+08,3,0.054177,1,0.397142,0
122,2017-12-27,600000.sh,12.65,12.66,12.53,12.62,12.64,3.27319e+07,4.12198e+08,3,0.116468,1,-0.158231,0
123,2017-12-28,600000.sh,12.6,12.66,12.53,12.54,12.62,2.38708e+07,3.00834e+08,3,0.084938,1,-0.633914,0
124,2017-12-29,600000.sh,12.52,12.62,12.51,12.59,12.54,1.63518e+07,2.05753e+08,3,0.058184,1,0.398726,0

In [23]:
result

,date,code,open,high,low,close,preclose,volume,amount,adjustflag,turn,tradestatus,pctChg,isST
0,2017-07-03,60000.sh,12.64,12.65,12.47,12.56,12.65,3.87789e+07,4.86265e+08,3,0.137985,1,-0.711456,0
1,2017-07-04,60000.sh,12.55,12.58,12.41,12.55,12.56,3.66591e+07,4.58434e+08,3,0.130442,1,-0.07962,0
2,2017-07-05,60000.sh,12.5,12.65,12.47,12.62,12.55,2.64705e+07,3.32542e+08,3,0.094188,1,0.557767,0
3,2017-07-06,60000.sh,12.62,12.72,12.51,12.66,12.62,3.74142e+07,4.71582e+08,3,0.133129,1,0.316957,0
4,2017-07-07,60000.sh,12.62,12.69,12.55,12.6,12.66,2.46673e+07,3.11102e+08,3,0.087772,1,-0.473929,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,2017-12-25,60000.sh,12.61,12.68,12.56,12.59,12.62,1.93067e+07,2.43554e+08,3,0.068698,1,-0.237716,0
121,2017-12-26,60000.sh,12.57,12.66,12.56,12.64,12.59,1.52257e+07,1.92219e+08,3,0.054177,1,0.397142,0
122,2017-12-27,60000.sh,12.65,12.66,12.53,12.62,12.64,3.27319e+07,4.12198e+08,3,0.116468,1,-0.158231,0
123,2017-12-28,60000.sh,12.6,12.66,12.53,12.54,12.62,2.38708e+07,3.00834e+08,3,0.084938,1,-0.633914,0
124,2017-12-29,60000.sh,12.52,12.62,12.51,12.59,12.54,1.63518e+07,2.05753e+08,3,0.058184,1,0.398726,0

In [8]:
result.to_csv(os.path.join(path, 'demo.csv'), encoding='gbk', index=False)

### 除权除息信息

In [9]:
rs_list = []

rs_dividend_2015 = bs.query_dividend_data(
    code=stock_code, 
    year='2015', 
    yearType='report'
)

while (rs_dividend_2015.error_code == '0') & rs_dividend_2015.next():
    rs_list.append(rs_dividend_2015.get_row_data())

In [10]:
result_dividend = pd.DataFrame(rs_list, columns=rs_dividend_2015.fields)

In [11]:
result_dividend

,code,dividPreNoticeDate,dividAgmPumDate,dividPlanAnnounceDate,dividPlanDate,dividRegistDate,dividOperateDate,dividPayDate,dividStockMarketDate,dividCashPsBeforeTax,dividCashPsAfterTax,dividStocksPs,dividCashStock,dividReserveToStockPs
0,sh.600000,,2015-05-16,2015-03-19,2015-06-16,2015-06-19,2015-06-23,2015-06-23,,0.757,0.6813或0.71915,0.000000,10派7.57元（含税，扣税后6.813或7.1915元）,